version: "3"

services:
  redis:
    image: redis:8
    ports:
      - "6379:6379"
  rabbit:
    image: rabbitmq:3.10-management
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"
  worker:
    build: .
    env_file: .env
    depends_on:
      - redis
      - rabbit
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities:
                - gpu
                - utility
                - compute
  fastapp:
    build: src/services/fastapi_app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - worker
  stapp:
    build: src/services/streamlit_app
    env_file: .env
    ports:
      - "8501:8501"
    depends_on:
      - fastapp

networks:
  app:
    driver: bridge
