real_esrgan_x2:
  scale: 2
  tile_size: 1000
  tile_pad: 100
  pre_pad: 10
  weights_path: "real_esrgan/weights/RealESRGAN_x2plus.pth"
  params:
    {
      num_in_ch: 3,
      num_out_ch: 3,
      num_feat: 64,
      num_block: 23,
      num_grow_ch: 32,
      scale: 2,
    }

real_esrgan_x4:
  scale: 4
  tile_size: 500
  tile_pad: 50
  pre_pad: 10
  weights_path: "real_esrgan/weights/RealESRGAN_x4plus.pth"
  params:
    {
      num_in_ch: 3,
      num_out_ch: 3,
      num_feat: 64,
      num_block: 23,
      num_grow_ch: 32,
      scale: 4,
    }

mlwnet:
  scale: 1
  tile_size: 800
  tile_pad: 200
  pre_pad: 10
  weights_path: "mlwnet/weights/realblur_j-width32.pth"
  params: { dim: 32 }

scunet:
  scale: 1
  tile_size: 1000
  tile_pad: 100
  pre_pad: 10
  weights_path: "scunet/weights/scunet_color_real_gan.pth"
  params: { in_nc: 3, config: [4, 4, 4, 4, 4, 4, 4], dim: 64 }
